# ── Server ──────────────────────────────
server.port=8080

# ── Application ─────────────────────────
app.base-url=https://interfascicular-rank-unforfeitable.ngrok-free.dev
app.short-code-length=6

# ── MySQL Database ───────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/urldb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ─────────────────────
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── QR Code ─────────────────────────────
app.qr.width=300
app.qr.height=300